#!/usr/bin/env python3
"""Third-party notices and SBOM for what the release actually ships (0111).

Writes docs/THIRD-PARTY-NOTICES.md (committed; `scripts/check.sh full` fails when it is stale) from the
Rust crates compiled into the workspace binaries (`cargo tree -e normal`) and the npm packages
bundled into the dashboard (runtime `dependencies`, transitively). With `--sbom PATH` also writes a
CycloneDX 1.5 JSON SBOM. With `--check` only reports whether the committed file is current.
No third-party tools: cargo and node_modules are the sources.

Needs a workspace that has been built once (`cargo` resolves the crate list) and `web/node_modules`
(`npm ci` in `web/`), because both halves are read from what is actually installed.
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "THIRD-PARTY-NOTICES.md")


def crates():
    fmt = "{p}\t{l}\t{r}"
    env = dict(os.environ, PATH=os.path.expanduser("~/.cargo/bin") + ":" + os.environ.get("PATH", ""))
    out = subprocess.run(["cargo", "tree", "--color", "never", "--workspace", "-e", "normal", "--prefix", "none", "-f", fmt],
                         cwd=ROOT, env=env, capture_output=True, text=True, check=True).stdout
    seen = {}
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        pkg, lic, repo = parts[0], parts[1], parts[2].replace(" (*)", "").strip()
        words = pkg.replace(" (*)", "").split()
        if len(words) < 2 or "(/" in pkg or words[0].startswith("sv10-"):
            continue  # workspace crates are ours
        name, version = words[0], words[1].lstrip("v")
        seen[(name, version)] = (lic or "UNKNOWN", repo)
    return sorted(seen.items())


def npm():
    base = os.path.join(ROOT, "web")
    # The list is read from the installed tree rather than the lockfile, so a fresh checkout that has
    # not run `npm ci` would fall through the loop below with nothing found and report the committed
    # notices as stale — a red gate on a clean clone with no hint of the cause. Say what to do.
    if not os.path.isdir(os.path.join(base, "node_modules")):
        sys.exit("notices.py: web/node_modules is missing; run `npm ci` in web/ first (the npm half "
                 "of this list comes from the installed packages, so notices cannot be generated or "
                 "checked without it)")
    top = json.load(open(os.path.join(base, "package.json"))).get("dependencies", {})
    todo, seen = list(top), {}
    while todo:
        name = todo.pop()
        path = os.path.join(base, "node_modules", name, "package.json")
        if name in seen or not os.path.exists(path):
            continue
        d = json.load(open(path))
        lic = d.get("license") or "UNKNOWN"
        repo = d.get("repository")
        repo = repo.get("url", "") if isinstance(repo, dict) else (repo or "")
        seen[name] = (d.get("version", "?"), lic if isinstance(lic, str) else json.dumps(lic), repo)
        todo.extend((d.get("dependencies") or {}).keys())
    return sorted(seen.items())


def render(rust, js):
    lines = ["# Third-party notices", "",
             "SvanBot is licensed MIT OR Apache-2.0 (LICENSE-MIT, LICENSE-APACHE). Its release binaries and",
             "dashboard include the following third-party packages under their own licenses; the full license",
             "texts ship inside each package's source (`vendor/` after `scripts/vendor.sh`, `web/node_modules/`).",
             "Generated by `scripts/notices.py`; do not edit by hand.", "",
             f"## Rust crates ({len(rust)})", "", "| Crate | Version | License | Repository |", "|---|---|---|---|"]
    lines += [f"| {n} | {v} | {l} | {r} |" for (n, v), (l, r) in rust]
    lines += ["", f"## Dashboard npm packages ({len(js)})", "", "| Package | Version | License | Repository |", "|---|---|---|---|"]
    lines += [f"| {n} | {v} | {l} | {r} |" for n, (v, l, r) in js]
    return "\n".join(lines) + "\n"


def sbom(rust, js, path):
    comps = [{"type": "library", "name": n, "version": v, "purl": f"pkg:cargo/{n}@{v}",
              "licenses": [{"expression": l}]} for (n, v), (l, _) in rust]
    comps += [{"type": "library", "name": n, "version": v, "purl": f"pkg:npm/{n.replace('@', '%40')}@{v}",
               "licenses": [{"expression": l}]} for n, (v, l, _) in js]
    version = next((l.split('"')[1] for l in open(os.path.join(ROOT, "Cargo.toml")) if l.startswith("version")), "0")
    doc = {"bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1,
           "metadata": {"component": {"type": "application", "name": "SvanBot", "version": version,
                                      "licenses": [{"expression": "MIT OR Apache-2.0"}]}},
           "components": comps}
    with open(path, "w") as f:
        json.dump(doc, f, indent=1)


def main():
    rust, js = crates(), npm()
    text = render(rust, js)
    if "--check" in sys.argv:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        if current != text:
            import difflib
            diff = difflib.unified_diff(current.splitlines(), text.splitlines(), "committed", "generated", lineterm="", n=0)
            print("\n".join(list(diff)[:40]), file=sys.stderr)
            print("docs/THIRD-PARTY-NOTICES.md is stale: run scripts/notices.py", file=sys.stderr)
            sys.exit(1)
        return
    open(OUT, "w").write(text)
    if "--sbom" in sys.argv:
        sbom(rust, js, sys.argv[sys.argv.index("--sbom") + 1])
    print(f"{len(rust)} crates, {len(js)} npm packages -> {OUT}")


main()
