#!/usr/bin/env python3
"""AI-provenance gate (0367), run by `scripts/check.sh`.

Every artifact in this repository is generated by an AI system and must say so: a
`Generated-by: <tool>/<model>` line in the commit footer, and the same line in the issue or pull
request body. The rule is stated in full in `CONTRIBUTING.md` section 0.

What this checks is *declaration*, not *authorship*. A trailer is self-reported and a person can
add one to hand-written code. The gate makes the convention mandatory and visible; review is what
makes it true. A clean run is not a guarantee about who wrote the code.

Merge commits are skipped (they carry no content of their own) and a commit whose author is already
`<name>[bot]` is exempt: `dependabot[bot]` and `github-actions[bot]` name their generator in the
author field, so a trailer would only repeat it.

  scripts/provenance.py check [<range>]        check commits, default range HEAD
  scripts/provenance.py check --pr-body FILE   check a pull request description as well
  scripts/provenance.py stamp                  print the trailer for this system
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# `<tool>` or `<tool>/<model>`, both restricted to characters that survive a copy-paste.
TRAILER = re.compile(r"^Generated-by:[ \t]*([A-Za-z0-9._+-]+(?:/[A-Za-z0-9._+-]+)?)[ \t]*$", re.M)
BOT_AUTHOR = re.compile(r"\[bot\]$")
# Record and field separators: control characters no commit message contains.
RECORD, FIELD = "\x1e", "\x1f"


def git(*args: str) -> str:
    """Run git in the repository root and return stdout, raising on failure."""
    done = subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True)
    if done.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {done.stderr.strip()}")
    return done.stdout


def commits(rev_range: str) -> list[tuple[str, str, str]]:
    """(sha, author, message) for each commit in the range, oldest first."""
    out = git("log", "--reverse", f"--format=%H{FIELD}%an{FIELD}%B{RECORD}", rev_range)
    rows = []
    for record in out.split(RECORD):
        record = record.strip("\n")
        if not record:
            continue
        sha, author, message = record.split(FIELD, 2)
        rows.append((sha, author, message))
    return rows


def is_merge(sha: str) -> bool:
    """True when the commit has more than one parent."""
    return len(git("rev-list", "--parents", "-n", "1", sha).split()) > 2


def trailer_in(text: str) -> str | None:
    """The system named by a `Generated-by:` line, or None."""
    found = TRAILER.search(text)
    return found.group(1) if found else None


def check_commits(rev_range: str, problems: list[str]) -> int:
    """Report commits in the range that name no generating system."""
    try:
        rows = commits(rev_range)
    except RuntimeError as e:
        problems.append(f"{rev_range}: cannot read commits ({e}); a shallow clone needs fetch-depth: 0")
        return 0
    checked = 0
    for sha, author, message in rows:
        if BOT_AUTHOR.search(author):
            continue  # The author field already names the system.
        try:
            if is_merge(sha):
                continue
        except RuntimeError:
            pass  # A parent we cannot read must not hide the commit from the check.
        checked += 1
        if not trailer_in(message):
            subject = message.strip().splitlines()[0] if message.strip() else "(no message)"
            problems.append(f"{sha[:12]}: no Generated-by trailer — {subject[:72]}")
    return checked


def check_pr_body(path: Path, problems: list[str]) -> None:
    """Report a pull request description that names no generating system."""
    if not path.exists():
        problems.append(f"{path}: pull request body not found")
        return
    if not trailer_in(path.read_text()):
        problems.append(f"{path}: no Generated-by line in the pull request body (CONTRIBUTING.md section 0)")


def stamp() -> int:
    """Print the trailer naming this system, for scripts/mirror.sh and for a human to copy."""
    system = os.environ.get("SVANBOT_GENERATED_BY", "").strip()
    if not system:
        print("provenance: set SVANBOT_GENERATED_BY to the system producing this work, e.g. claude-code/opus-5", file=sys.stderr)
        return 1
    if not TRAILER.match(f"Generated-by: {system}"):
        print(f"provenance: SVANBOT_GENERATED_BY={system!r} is not <tool> or <tool>/<model>", file=sys.stderr)
        return 1
    print(f"Generated-by: {system}")
    return 0


def main(argv: list[str]) -> int:
    if not argv or argv[0] not in ("check", "stamp"):
        print(__doc__.strip(), file=sys.stderr)
        return 2
    if argv[0] == "stamp":
        return stamp()

    body = None
    rest = argv[1:]
    if "--pr-body" in rest:
        i = rest.index("--pr-body")
        if i + 1 >= len(rest):
            print("provenance: --pr-body needs a file", file=sys.stderr)
            return 2
        body = Path(rest[i + 1])
        rest = rest[:i] + rest[i + 2 :]
    rev_range = rest[0] if rest else "HEAD"

    problems: list[str] = []
    checked = check_commits(rev_range, problems)
    if body is not None:
        check_pr_body(body, problems)
    for p in problems:
        print(p)
    if problems:
        print(f"provenance: {len(problems)} artifact(s) name no generating system", file=sys.stderr)
        return 1
    print(f"provenance: {checked} commit(s) in {rev_range} name their system", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
