#!/usr/bin/env python3
"""AI-provenance gate (0367), run by `scripts/check.sh`.

Every artifact in this repository is generated by an AI system and must say so: a
`Generated-by: <tool>/<model>` line in the commit footer, and the same line in the issue or pull
request body. The rule is stated in full in `CONTRIBUTING.md` section 0.

What this checks is *declaration*, not *authorship*. A trailer is self-reported and a person can
add one to hand-written code. The gate makes the convention mandatory and visible; review is what
makes it true. A clean run is not a guarantee about who wrote the code.

Merge commits are skipped (they carry no content of their own) and a commit whose author is already
`<name>[bot]` is exempt: `dependabot[bot]` and `github-actions[bot]` name their generator in the
author field, so a trailer would only repeat it.

`report` writes `AI-PROVENANCE.md`: the systems on record, read from the same trailers. Its `--check`
compares the **set** of systems, not the counts beside them — a count moves with every commit, so a
document that had to be regenerated per commit would conflict in every branch and be regenerated by
nobody. A system appearing for the first time is therefore a red gate until someone runs `report`,
which is the drift this exists to make visible.

  scripts/provenance.py check [<range>]        check commits, default range HEAD
  scripts/provenance.py check --pr-body FILE   check a pull request description as well
  scripts/provenance.py stamp                  print the trailer for this system
  scripts/provenance.py report [--check]       write AI-PROVENANCE.md, or say whether it is current
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# `<tool>` or `<tool>/<model>`, both restricted to characters that survive a copy-paste.
TRAILER = re.compile(r"^Generated-by:[ \t]*([A-Za-z0-9._+-]+(?:/[A-Za-z0-9._+-]+)?)[ \t]*$", re.M)
BOT_AUTHOR = re.compile(r"\[bot\]$")
# Record and field separators: control characters no commit message contains.
RECORD, FIELD = "\x1e", "\x1f"


def git(*args: str) -> str:
    """Run git in the repository root and return stdout, raising on failure."""
    done = subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True)
    if done.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {done.stderr.strip()}")
    return done.stdout


def commits(rev_range: str) -> list[tuple[str, str, str]]:
    """(sha, author, message) for each commit in the range, oldest first."""
    out = git("log", "--reverse", f"--format=%H{FIELD}%an{FIELD}%B{RECORD}", rev_range)
    rows = []
    for record in out.split(RECORD):
        record = record.strip("\n")
        if not record:
            continue
        sha, author, message = record.split(FIELD, 2)
        rows.append((sha, author, message))
    return rows


def is_merge(sha: str) -> bool:
    """True when the commit has more than one parent."""
    return len(git("rev-list", "--parents", "-n", "1", sha).split()) > 2


def trailer_in(text: str) -> str | None:
    """The system named by a `Generated-by:` line, or None."""
    found = TRAILER.search(text)
    return found.group(1) if found else None


def check_commits(rev_range: str, problems: list[str]) -> int:
    """Report commits in the range that name no generating system."""
    try:
        rows = commits(rev_range)
    except RuntimeError as e:
        problems.append(f"{rev_range}: cannot read commits ({e}); a shallow clone needs fetch-depth: 0")
        return 0
    checked = 0
    for sha, author, message in rows:
        if BOT_AUTHOR.search(author):
            continue  # The author field already names the system.
        try:
            if is_merge(sha):
                continue
        except RuntimeError:
            pass  # A parent we cannot read must not hide the commit from the check.
        checked += 1
        if not trailer_in(message):
            subject = message.strip().splitlines()[0] if message.strip() else "(no message)"
            problems.append(f"{sha[:12]}: no Generated-by trailer — {subject[:72]}")
    return checked


def check_pr_body(path: Path, problems: list[str]) -> None:
    """Report a pull request description that names no generating system."""
    if not path.exists():
        problems.append(f"{path}: pull request body not found")
        return
    if not trailer_in(path.read_text()):
        problems.append(f"{path}: no Generated-by line in the pull request body (CONTRIBUTING.md section 0)")


def roster_path() -> Path:
    """Where the roster lives. A function, not a constant: the tests point ROOT at a scratch repository."""
    return ROOT / "AI-PROVENANCE.md"


def recorded(rev_range: str = "HEAD") -> list[tuple[str, str]]:
    """(system, date) for each commit in the range that names one, oldest first.

    A commit that names no system is not an error here — `check` is what reports those, and a bot
    author is exempt from carrying a trailer at all — it is simply absent from the roster.
    """
    out = git("log", "--reverse", f"--format=%aI{FIELD}%B{RECORD}", rev_range)
    rows = []
    for record in out.split(RECORD):
        record = record.strip("\n")
        if not record:
            continue
        date, message = record.split(FIELD, 1)
        system = trailer_in(message)
        if system:
            rows.append((system, date[:10]))
    return rows


def render_roster(rows: list[tuple[str, str]]) -> str:
    """The whole `AI-PROVENANCE.md` body for these (system, date) rows."""
    systems: dict[str, list[str]] = {}
    for system, date in rows:
        systems.setdefault(system, []).append(date)
    # Oldest first: the order the systems arrived in is the part that cannot be read off a single
    # line, and it is stable — a new system appends, it does not re-sort the table.
    order = sorted(systems, key=lambda s: (systems[s][0], s))
    as_of = max((d for dates in systems.values() for d in dates), default="—")
    lines = [
        "# AI provenance",
        "",
        "SvanBot is written by AI systems, and every artifact in this repository says which one: a",
        "`Generated-by: <tool>/<model>` trailer in a commit's footer, and the same line in the body of an",
        "issue or a pull request. The rule is stated in `CONTRIBUTING.md` section 0; `scripts/provenance.py check`",
        "enforces it, in `scripts/check.sh` and in CI over the commits a pull request proposes and its",
        "description. Generated by `scripts/provenance.py report`; do not edit by hand.",
        "",
        "## What this does not prove",
        "",
        "A trailer is **self-reported**. What the gate enforces is *declaration*, not authorship — a person",
        "can add a trailer to hand-written code and no check can tell. This page is the roster of systems on",
        "record, not a claim about who wrote any particular line: review is what makes a trailer true, and a",
        "clean run of the gate is not evidence about authorship.",
        "",
        "## The systems on record",
        "",
        f"The counts and dates are a snapshot as of {as_of}, taken from the `Generated-by:` trailers in this",
        "repository's history. The check that keeps this page current compares the **set of systems**, not the",
        "counts: a count changes with every commit, so a document that had to be regenerated per commit would",
        "conflict in every branch and be regenerated by nobody. A system that appears here for the first time",
        "is a red gate until someone regenerates the file.",
        "",
        "| System | Commits | First | Last |",
        "|---|---|---|---|",
    ]
    lines += [f"| {s} | {len(systems[s])} | {systems[s][0]} | {systems[s][-1]} |" for s in order]
    lines += [
        "",
        "## Regenerating",
        "",
        "```sh",
        "scripts/provenance.py report          # rewrite this file",
        "scripts/provenance.py report --check  # fail when a system is missing from it",
        "```",
        "",
    ]
    return "\n".join(lines)


def roster_systems(text: str) -> set[str]:
    """The systems a roster table names: the first column of each body row."""
    systems = set()
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        # Body rows only: the header (`System`), the `|---|` separator, and any prose wrapped in pipes.
        if len(cells) != 4 or not cells[0] or cells[0] == "System" or set(cells[0]) <= set("-"):
            continue
        systems.add(cells[0])
    return systems


def report(check: bool, rev_range: str = "HEAD") -> int:
    """Write `AI-PROVENANCE.md`, or say whether the systems it lists are the ones in the history."""
    text = render_roster(recorded(rev_range))
    live = roster_systems(text)
    path = roster_path()
    if not check:
        path.write_text(text)
        print(f"{len(live)} system(s) in {rev_range} -> {path}")
        return 0
    committed = roster_systems(path.read_text()) if path.exists() else set()
    if committed == live:
        print(f"provenance: {path.name} lists the {len(live)} system(s) in {rev_range}")
        return 0
    for system in sorted(live - committed):
        print(f"{path.name} does not list {system}, which has commits in {rev_range}")
    for system in sorted(committed - live):
        print(f"{path.name} lists {system}, which no commit in {rev_range} names")
    print(f"provenance: {path.name} is not the roster of {rev_range}: run scripts/provenance.py report", file=sys.stderr)
    return 1


def stamp() -> int:
    """Print the trailer naming this system, for scripts/mirror.sh and for a human to copy."""
    system = os.environ.get("SVANBOT_GENERATED_BY", "").strip()
    if not system:
        print("provenance: set SVANBOT_GENERATED_BY to the system producing this work, e.g. claude-code/opus-5", file=sys.stderr)
        return 1
    if not TRAILER.match(f"Generated-by: {system}"):
        print(f"provenance: SVANBOT_GENERATED_BY={system!r} is not <tool> or <tool>/<model>", file=sys.stderr)
        return 1
    print(f"Generated-by: {system}")
    return 0


def main(argv: list[str]) -> int:
    if not argv or argv[0] not in ("check", "stamp", "report"):
        print(__doc__.strip(), file=sys.stderr)
        return 2
    if argv[0] == "stamp":
        return stamp()
    if argv[0] == "report":
        rest = [a for a in argv[1:] if a != "--check"]
        return report("--check" in argv[1:], rest[0] if rest else "HEAD")

    body = None
    rest = argv[1:]
    if "--pr-body" in rest:
        i = rest.index("--pr-body")
        if i + 1 >= len(rest):
            print("provenance: --pr-body needs a file", file=sys.stderr)
            return 2
        body = Path(rest[i + 1])
        rest = rest[:i] + rest[i + 2 :]
    rev_range = rest[0] if rest else "HEAD"

    problems: list[str] = []
    checked = check_commits(rev_range, problems)
    if body is not None:
        check_pr_body(body, problems)
    for p in problems:
        print(p)
    if problems:
        print(f"provenance: {len(problems)} artifact(s) name no generating system", file=sys.stderr)
        return 1
    print(f"provenance: {checked} commit(s) in {rev_range} name their system", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
