#!/usr/bin/env bash
# Render this checkout's systemd user units and install them (#15).
#
# The shipped units in scripts/ are templates: they name the checkout as @SVANBOT_ROOT@ and nothing
# else. This script fills that in with the directory it is run from, so the installed units point at
# the checkout that produced them rather than at whatever path the machine they were written on
# happened to use. Relocating an install is then: stop, move the checkout, run this again,
# `systemctl --user daemon-reload` (done here), start.
#
#   scripts/units.sh              render every unit and install it, then reload systemd
#   scripts/units.sh --check      name any unit that is missing or was rendered for another checkout
#   scripts/units.sh --print U    write one rendered unit to stdout (U as named in scripts/)
#   scripts/units.sh --setup      render, install, and enable the service and the timers for boot
#                                 where a user systemd instance answers; where none does, install
#                                 and say how to enable by hand. scripts/setup.sh runs this after a
#                                 successful release, so a fresh install starts on boot.
#
# DEST overrides where units are written (default $XDG_CONFIG_HOME/systemd/user, else
# ~/.config/systemd/user). Enabling outside `--setup` stays an operator decision:
# scripts/archive-timer.sh enables the archive and cleanup timers, and
# `systemctl --user enable svanbot10.service` is the autostart row in docs/OPERATIONS.md.
set -euo pipefail
cd "$(dirname "$0")/.."
root=$(pwd -P)
dest="${DEST:-${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user}"

fail() { printf 'units.sh: %s\n' "$*" >&2; exit 1; }

# A unit file is one line per setting, so a checkout path holding a newline cannot be written at all,
# and a `"` would close the quoting the Exec lines use to survive a path with spaces. Both are legal
# in a Linux path and neither is expressible here: say so rather than emit a unit systemd misreads.
case "$root" in
  *'"'*) fail "the checkout path contains a double quote, which a unit file's Exec line cannot carry: $root" ;;
esac
[ "$root" = "${root%$'\n'*}" ] || fail "the checkout path contains a newline, which a unit file cannot carry"
# `%` starts a systemd specifier (`%h` is the home directory, and the templates use it deliberately),
# so a `%` coming from the *path* has to be doubled or systemd expands or rejects it.
escaped="${root//%/%%}"

templates=()
for f in scripts/svanbot10*.service scripts/svanbot10*.timer; do
  [ -f "$f" ] && templates+=("$f")
done
[ "${#templates[@]}" -gt 0 ] || fail "no unit templates in scripts/"

# Literal substitution, done by hand. Every replacement operator within reach reads something in the
# replacement text as syntax — `&` and `\1` in sed and awk, and `&` in bash's own `${v//pat/rep}`,
# which since 5.2 expands an unquoted one to the matched text — and a home directory is free to
# contain any of them. `/home/a & b/SvanBot` rendered through `${line//@SVANBOT_ROOT@/$root}` puts
# the placeholder back into the unit.
#
# The template's own header — the lines before its first `[Section]` — says it is a template and is
# dropped here, so the installed file says instead where it came from and which checkout it was
# rendered for. That header is the answer to "is this unit the one this checkout would write?" read
# straight out of ~/.config/systemd/user, and `--check` is the same question asked exactly.
fill() {
  local rest="$1" out=""
  while [ "${rest#*@SVANBOT_ROOT@}" != "$rest" ]; do
    out="$out${rest%%@SVANBOT_ROOT@*}$escaped"
    rest="${rest#*@SVANBOT_ROOT@}"
  done
  printf '%s\n' "$out$rest"
}

render() {
  printf '# Generated by scripts/units.sh from %s; re-render it after moving the checkout.\n' "$1"
  printf '# checkout: %s\n' "$root"
  local line body=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$body" = 0 ]; then
      case "$line" in '['*) body=1 ;; *) continue ;; esac
    fi
    fill "$line"
  done < "$1"
}

mode=install
case "${1:-}" in
  --check) mode=check ;;
  --setup) mode=setup ;;
  --print)
    [ -n "${2:-}" ] || fail "--print needs a unit name, e.g. --print svanbot10.service"
    [ -f "scripts/$2" ] || fail "no such unit template: scripts/$2"
    render "scripts/$2"
    exit 0
    ;;
  "") ;;
  *) fail "unknown argument $1 (--check | --setup | --print UNIT)" ;;
esac

if [ "$mode" = check ]; then
  drift=0
  for t in "${templates[@]}"; do
    name=${t##*/}
    if [ ! -f "$dest/$name" ]; then
      printf '%-34s not installed\n' "$name"
      drift=1
    elif ! render "$t" | cmp -s - "$dest/$name"; then
      printf '%-34s installed copy differs from this checkout\n' "$name"
      drift=1
    fi
  done
  [ "$drift" = 0 ] || { printf 'units.sh: run scripts/units.sh to render them for %s\n' "$root" >&2; exit 1; }
  printf 'units: %d installed for %s\n' "${#templates[@]}" "$root"
  exit 0
fi

mkdir -p "$dest"
for t in "${templates[@]}"; do
  name=${t##*/}
  tmp="$dest/.$name.rendered"
  render "$t" > "$tmp"
  if [ -f "$dest/$name" ] && cmp -s "$tmp" "$dest/$name"; then
    rm -f "$tmp"
    printf '%-34s unchanged\n' "$name"
  else
    mv -f "$tmp" "$dest/$name"
    printf '%-34s written\n' "$name"
  fi
done
printf 'checkout %s\nunits    %s\n' "$root" "$dest"

# A machine without a user systemd instance (a container, CI) still gets the rendered files; only the
# reload is skipped, and saying so beats a red exit from a step that was never the point.
if [ -n "${DEST:-}" ]; then
  echo "DEST set: not reloading systemd."
elif systemctl --user daemon-reload 2>/dev/null; then
  echo "systemd reloaded. Enable what you want: systemctl --user enable --now svanbot10.service"
else
  echo "No user systemd instance here; units written, reload skipped."
fi

if [ "$mode" = setup ]; then
  # Boot persistence for a fresh install (#463): the fleet service plus the keepalive, archive and
  # cleanup timers. The probe and the enable are guarded, so a box without systemd gets one honest
  # line and a zero exit rather than a failed setup; enabling is idempotent, so re-running setup or
  # scripts/archive-timer.sh settles any partial state.
  boot_units=(svanbot10.service svanbot10-keepalive.timer svanbot10-archive.timer svanbot10-clean.timer)
  if systemctl --user daemon-reload >/dev/null 2>&1 \
  && systemctl --user enable "${boot_units[@]}" >/dev/null 2>&1; then
    printf 'units enabled for boot: %s\n' "${boot_units[*]}"
  else
    printf 'No systemd user instance here; units rendered but not enabled.\n'
    printf 'Where systemd exists, enable them: systemctl --user enable --now %s\n' "${boot_units[*]}"
  fi
fi
