
export const panelHelp: Record<string, string> = {
  'Wiring table': 'Is every part of the bot really changing its play? The analyst re-runs the newest recorded big decisions with one component switched off at a time, on the same cards and samples, and counts how many choices move and what the moved choice gives up under the full model. A component that moves nothing is not a lever; one whose removal costs chips is earning its place. Re-measured daily.',
  'Decision accuracy': 'How well the bots decide, chess-style: the analyst re-solves big decisions with far more samples, and each live choice is graded by the EV it gave up against the deep search\'s best, as a share of the pot (Best under 2%, Good 10%, Inaccuracy 20%, Mistake 40%, Blunder beyond). Accuracy uses Lichess\'s formula. Try the Quiz to play the same spots yourself.',
  'Stories': 'The last 24 hours as a recap (each bot, the fleet, the pot and the cooler of the day) and this season as a timeline: every time the fleet crossed another 100,000 chips, and the three biggest pots.',
  'Unified event timeline': 'In Results, scrub the current season hour by hour. Each bar shows stored hands and net chips; marks come from release records, dated operator changes, learner promotions, the season boundary and stored warnings or errors. Pick an hour to open its exact hand rows and event source. Zero hands means no recorded play, not a diagnosis of why.',
  'Badge race': 'Season-end rewards: the top 3 by score earn permanent Gold/Silver/Bronze badges (10-hand minimum) and the top 30 share the prize pool, one winning bot per owner. Each bot shows its rank on the score, win-rate (share of hands won) and hands-played boards, and the points it still needs for bronze. Refreshed every 5 minutes.',
  'Rivals': 'Opponents we have shared 150+ hands with, ranked by the bb/100 that moved between us and them (chips they won from us minus chips we won from them) over every stored hand of champion play — the experiment arms\' treatment hands are excluded from the ledger, because its verdict moves the fleet between tables and a challenger is not the policy that plays there. WANTED marks a player who beats us at 95% and FAN CLUB one we beat at 95%, both corrected for the number of opponents tested so luck alone does not earn a badge. Avatars appear once the player has sat at one of our tables. The interval matters: a big number over few hands is usually luck.',
  'Per-opponent reads': 'Three per-opponent reads on top of the shared model: how often each opponent folds to our bets, how they answer a bet compared with the neural response model, and how their river bet size tracks their hand strength. The learner refits all three every cycle; a read is used in live decisions only while it predicts newer hands better than the shared model (held-out gain above its 95% band). Click a name for the scout view, which lists the corrections in force for that player.',
  'Season race': 'Live public leaderboard (refreshed every minute). Our bots are highlighted, arrows show rank movement since the last refresh, and the bar shows each score relative to the leader.',
  'Self-calibration': 'The bot compares the expected value it predicted for each decision with the chips that decision really won, grouped by spot. Consistent gaps over many hands become small capped EV corrections that the live policy applies automatically.',
  'Live action': 'Every action, board card, decision and hand result, pushed the instant it happens. Switch between the selected bot and the whole fleet.',
  'Fleet race': 'Cumulative chips won by every bot over its hands. Click a name to hide or show its line; hover a line to read the value at that hand.',
  'Highlights': 'Achievements unlocked by the fleet plus its most memorable hands. Click any hand to replay it action by action.',
  'Autonomy': "The learner runs in its own process. Each cycle it builds simulated clones of the 16 most-observed opponents. Each clone plays that opponent's full learned profile (positional opens, 3-bets, folds to 3-bets, c-bets, size-aware folds, raises, river bluffs), with rates redrawn within their sampling error. Parameter nudges compete on identical deals, and the better half keeps getting more hands. The survivor must then win on fresh deals: up to four chunks, promoted only on a positive 95% lower bound (or overwhelming evidence early). It stops as soon as it is clearly not ahead.",
  'Experiments': 'Completed champion evaluations from the promotion history: who was tested, whether it promoted, and the evidence behind the call.',
  'Runtime health': 'Connection and process state for the selected bot. Modes: playing (connected), connecting (retrying with backoff), paused, stopped. A non-zero learner failure count means training cycles are erroring — check the log.',
  'Live table': 'The latest table state received from the server, pushed the moment it arrives. THINKING marks the seat the server says is acting; it does not prove a calculation is still running. The decision strip shows the latest answered turn, which may be from an earlier hand.',
  'Starting hand library': "Computed from the live policy itself: for every hand class and position, whether the current champion (with today's opponent models, parameters and neural response model) open-raises when folded to at 100 bb. The BB tab shows hands defended against a button open. It refreshes as models and parameters change; facing limps or raises the live decision can differ.",
  'Recent hands': 'Completed hands with recorded results in big blinds, plus your hole cards and the board where shown. Select a hand to replay your recorded decisions street by street.',
  'Opponent intelligence': 'Every observed player, most-seen first, with four headline rates and the hands-observed count behind them. Hands are counted from live tables plus downloaded histories, older hands weighing less, and the rates are shrunk toward the population until a player has enough evidence; the style label is a rule-of-thumb summary, not an input. Click a player for their scout view: the full rate set beside the league, positional opens, c-bets, folds by street and bet size, showdown bluffs, our record against them and the corrections in force.',
  'Performance': 'Cumulative recorded winnings for the selected bot. BB means big blind; bb/100 is the average result per 100 recorded hands. Early numbers are noise — the promotion gate demands statistical significance for the same reason.',
  'Champion profile': 'The live champion (latest promoted lineage entry) and the parameters every decision uses. The learner nudges one parameter at a time and promotes only after fresh-deal confirmation, so these values move slowly and each change is in the Experiments panel with its evidence.',
  'Season ledger': 'Totals reported by the poker server. Off-table chips, chips at the table, score, and hand profit are different quantities. Buy-ins and rebuys move chips and are not poker winnings.',
  'Results monitor': 'The read-only results monitor (the `monitor` binary): every 30 minutes the fleet result per bot, who we lost most to and won most from, and the opponents we played most with their style and our result; alerts for big wins and losses (250 bb or more), opponents beating us at 95% confidence, stalled bots and fleet errors. Also machine pressure, how many big decisions are recorded for replay, and the last season-boundary check.',
  'Activity log': 'Recent connection, recovery, strategy, and training messages. Filter the log to investigate a specific event.',
  'Experiment mode': 'The live arm of the champion/challenger test: while the fleet holds the top four leaderboard places, the bot sitting fourth and the fifth bot play one arm each — the champion against a challenger whose simulated estimate is positive. Arms switch only at a hand boundary, treatment hands are kept out of every fit, and live results never promote anyone by themselves: a challenger still has to clear the promotion gate on fresh dealt hands. Every other bot always plays the champion.',
  'Range explorer': 'The ranges the live policy reconstructed for each opponent at our last decision, replayed from their actions and learned profile: brighter combos are more likely, and the footer gives our equity against that range, the profile behind it and the most likely hands. It refreshes with each new decision; until the bot has faced live opponents it says so rather than drawing an empty grid.',
  'Releases & updates': 'Where the installed build came from and what a one-click update brings: the commits from GitHub since it, the stage a run is in with the time each stage usually takes, and whether the bots are still playing (they are — the fleet swaps to the new build between turns). Every update saves the build it replaces, and a saved build can be reinstalled after its hashes are checked. A failed step installs nothing.',
  'Host check': 'Read-only facts about the machine the fleet runs on, each marked ok, worth a look, or for context, with advice where something is off. It reads; it never changes the host.',
  'Leak finder': "Every recorded hand grouped into leaks: the analyst's advice, the lines we take and how they end, results by position and by opponent, whether the calibrated exploits still pay, and the trend across the season. It reads stored hands only, so it lags live play.",
};

export function HelpPage() {
  return <main className="help-page" aria-label="Bot help">
    <a className="text-button" href="#">← Back to control room</a>
    <span className="eyebrow">SVANBOT 10 GUIDE</span><h1>What is the bot doing?</h1>
    <p className="help-intro">Live play and background training are separate jobs. You can watch them here, but keeping this page open is not required.</p>
    <nav className="help-nav" aria-label="Help topics">{[['thinking','Thinking and waiting'],['decisions','How decisions work'],['champion','Champion and training'],['numbers','Reading the numbers'],['controls','Controls and recovery']].map(([id,label])=><a key={id} href={`#help/${id}`}>{label}</a>)}</nav>
    <section id="thinking"><h2>What “Thinking” means</h2><p>The table marks the seat whose turn the server says it is. For another player, it means we are waiting for that player. For our bot, it covers pricing every legal action, sending one, and waiting for the next server update. It is not a live CPU indicator.</p><p>Each turn has a 45-second public deadline. The bot answers in milliseconds to a few hundred milliseconds (the panel shows measured latency) and falls back to check-or-fold after 8 seconds. If the table seems stuck, check the connection status, the last update time and the activity log.</p></section>
    <section id="decisions"><h2>How a decision happens</h2><ol><li>The server sends the turn: legal actions, raise limits and a turn token (each token is answered once).</li><li>Every live opponent's range is rebuilt from their actions this hand, weighted by their own learned tendencies. The shape constants are fitted to real showdowns.</li><li>Hero's equity against those ranges comes from Monte Carlo deals shared across all candidates, so the options are compared on the same cards.</li><li>Each option is priced in chips: fold, check or call, and several raise sizes. For raises, each opponent's fold chance comes from their stats (and the neural response model when it beats the stats on held-out hands). Hands that continue are narrowed, re-raises are priced from their 3-bet, 4-bet and raise-vs-bet rates, and all-in players keep their share of the pot.</li><li>Small learned per-spot corrections (self-calibration) are added. The best option is chosen, mixing only between near-equal ones, then legalized against the offer and sent with the hand id and turn token.</li></ol></section>
    <section id="champion"><h2>Champion and automatic training</h2><p>The champion is the parameter set live play uses, named by its lineage entry (sv10-ev-N). The learner proposes one-parameter nudges and screens them by successive halving in paired simulations. Both sides play identical deals against profile clones of the real opponents, with all-in luck removed. The best candidate is promoted only if it also wins on fresh deals with a positive 95% lower bound. Running bots pick up the new parameters within seconds, and every decision records the version that made it.</p><p>Every evaluation, promoted or rejected, is saved to the Experiments panel with its evidence. Training runs in its own process and paces itself by new live hands, so it never slows live decisions.</p></section>
    <section id="numbers"><h2>Reading the numbers</h2><dl><dt>Range equity</dt><dd>Estimated share of the pot at showdown from Monte Carlo simulation, including split pots, over 2,500 shared deals by default (tuned to the CPU). It is not the probability that a bet makes money. When the simulation cannot produce the deals it was asked for, no equity is reported at all and the decision falls back to the safe action — check where the rules allow it, fold otherwise — rather than answering from a handful of deals.</dd><dt>Pot odds</dt><dd>Call cost divided by the pot after calling. Calling 20 into a pot of 80 gives 20% pot odds.</dd><dt>Samples</dt><dd>Monte Carlo rollouts behind the equity number. More samples means less simulation noise — not more certainty about opponents.</dd><dt>Preflop score</dt><dd>1 minus the hand class's preflop strength percentile (AA ≈ 1, 72o ≈ 0). The threshold is the weakest score the live opening guide still opens first-in from your position, recomputed from the current opponent models and parameters. The EV policy makes the actual decision, so facing a raise it can differ from the guide.</dd><dt>Opponent profiles</dt><dd>VPIP (voluntarily entering pots) and PFR (raising preflop) counted from real observed hands, with sample counts. Style is the nearest reference cluster, a summary, not a verdict.</dd><dt>Range model</dt><dd>How the bot reconstructs an opponent's likely hands from their actions. Its shape constants are fitted to real showdowns; the nats figure is how much more likely the actually-shown hands were under the model than under a blind guess (higher is better), measured on the newest showdowns the fit never saw.</dd><dt>Past-season hands</dt><dd>Every hand our bots ever played, downloaded from the server's history export and folded into opponent statistics (older hands count less) and neural-model training.</dd><dt>bb/100</dt><dd>Average big blinds won per 100 recorded hands. Small samples are noise; the promotion gate requires significance before acting on an edge.</dd></dl></section>
    <section id="controls"><h2>Controls and recovery</h2><p>Start, Pause, and Stop act per bot seat. Pause drops the connection; the server holds the seat for 120 seconds, so a prompt resume usually lands back at the same table, while a long pause rejoins fresh. If a connection drops on its own, the seat reconnects with backoff and resynchronizes; auth failures stop the seat instead of retrying a bad key.</p><p>The information button on each panel explains that panel. The chevron minimizes it to a heading bar and remembers your preference in this browser. Minimizing a panel or closing the page does not stop play or training.</p><p>The service must remain running on the host computer. Runtime health and the activity log show what recovery is doing. Hand results, opponent observations, and training evidence are stored server-side and survive restarts.</p></section>
  </main>;
}
